---
- name: clone service watch | git
  sudo_user: "{{ servicewatch_user }}"
  git:
    repo: "https://github.com/telusdigital/service-watch.git"
    dest: "{{ servicewatch_path }}"
    update: yes
    force: yes

- name: install | npm
  sudo_user: "{{ servicewatch_user }}"
  shell: "cd {{ servicewatch_path }} && node install.js"

- name: copy configuration
  sudo_user: "{{ servicewatch_user }}"
  template:
    src: templates/config.js
    dest: "{{ servicewatch_path }}/alerts/slack/config.js"
    mode: 0644

# - name: set cron jobs
#   sudo_user: "{{ servicewatch_user }}"
#   cron:
#     name: "cron for github mfa checker"
#     user: "{{ servicewatch_user }}"
#     special_time: daily
#     job: "node {{ servicewatch_path }}/service-watch.js"
